DROP TABLE IF EXISTS CABDRIVER;
CREATE TABLE CABDRIVER(  
driverID INT AUTO_INCREMENT  PRIMARY KEY,  
DRIVER_NAME VARCHAR(50) NOT NULL UNIQUE,  
DRIVER_EMAIL VARCHAR(50) NOT NULL UNIQUE,
PHONE_NUMBER INT(10) NOT NULL UNIQUE,
LICENSE_NUMBER VARCHAR(50) NOT NULL UNIQUE,
CAR_NUMBER VARCHAR(50) NOT NULL UNIQUE
);  
